# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd02609e5cb8916e1835b528ffe86b0d85ad80449f651eea60f40e96502652e90cd9a0d1373a052cb6d837d0f5a0377e548ea121aca231dbde0f6e5a0e57b0b0

test:
  secret_key_base: 18e900de96b59971ed2ee51e82286d6fd4ad151b89f3da23aec831496b5b2cc6dec947c2cbcac0feac48e984f0cce6064f8248f813471be803916790bd041b77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
